### ISSUE TITLE
README.md is out-of-date

### ISSUE THREAD

**Issue by davepuchyr** [Zondax/ledger-namada#26]
From the README:

```
Download a release from here (https://github.com/Zondax/ledger-namada/releases). You only need installer.sh
```

However, `installer.sh` does not exist!

Also, what version of the install script should Nano X users use?  I've tried all 3 scripts with the Nano X and they all yield

```
ledgerblue.commException.CommException: Exception : Invalid status 6814 (Unknown reason)
```

My Ledger is able to sign txs with the Cosmos, Ethereum, and Solana apps, so it's not a connectivity issue.

**Comment by ftheirs** [comment]
Hi @davepuchyr, in the release section you will find with every new release 3 installer scripts.
- installer_nanos.sh is for NanoS devices
- installer_nanos_plus.sh is for NanoS+ devices
- installer_stax.sh is for Stax devices

Unfortunately, NanoX devices doesn't allow side loading the app. However, Namada app is already available in LedgerLive, you just need to enable the developer mode
