### ISSUE TITLE
Nano X

### ISSUE THREAD

**Issue by zenodeapp** [Zondax/ledger-namada#35]
Hey!

I was wondering which binaries are compatible with the Nano X, wasn't sure which to choose since I only see the ones for Nano S, S Plus and Stax.

**Comment by ftheirs** [comment]
Hey @zenodeapp, NanoX doesn't allow side loading apps. You can only install apps from Ledger Live

**Comment by zenodeapp** [comment]
> Hey @zenodeapp, NanoX doesn't allow side loading apps. You can only install apps from Ledger Live

Oh I did not know! Thank you.

I also have an S where it's working wonderfully but wanted to try it out on my main, unfortunately v0.16 isn't working with the Shielded Expedition.

But that's alright! Thanks for the explanation :)!
