### ISSUE TITLE
ZIP 32 Support

### ISSUE THREAD

**Issue by murisi** [Zondax/ledger-namada#52]
The Ledger app does not seem to support ZIP 32 paths. This is problematic because the Namada wallet uses these for MASP keys and addresses. For instance attempting to execute `app.retrieveKeys(hdpath, NamadaKeys.ProofGenerationKey, false)` with `hdpath` set to `m/32'/877'/0'` yields the return code 0x6700 (`APDU_CODE_WRONG_LENGTH`). Would it be possible to add ZIP 32 support (i.e paths and key derivations) to the Ledger Namada app? Or maybe point to documentation of its usage if ZIP 32 support is already there and I'm using the API incorrectly?

**Comment by chcmedeiros** [comment]
Hey @murisi we were not supporting Zip32, but we will add the support.

**Comment by murisi** [comment]
Thanks @chcmedeiros . Also, would it be possible for the Ledger app to generate and display extended full viewing keys at the account level of the ZIP 32 hierarchy, and provide it amongst the app's key responses? Doing this would ease integration with `namadaw` which currently only supports importing extended full viewing keys and payment addresses.

**Comment by murisi** [comment]
> Thanks @chcmedeiros . Also, would it be possible for the Ledger app to generate and display extended full viewing keys at the account level of the ZIP 32 hierarchy, and provide it amongst the app's key responses? Doing this would ease integration with `namadaw` which currently only supports importing extended full viewing keys and payment addresses.

Hi again @chcmedeiros ! Would it be possible to provide support for extended full viewing keys at a minimum? Our CLI and web clients only support extended full viewing keys as inputs (and the MASP library only supports extended spending keys for building transactions). I'm thinking that an approach similar to https://github.com/Zondax/ledger-namada/pull/61 or a subset of it could be used to achieve this goal...
