### ISSUE TITLE
Check `shielded_hash` inside `Transfer`s

### ISSUE THREAD

**Issue by murisi** [Zondax/ledger-namada#67]
The hardware wallet currently checks whether the `MaspBuilder` section targets the attached MASP `Transaction` here: https://github.com/Zondax/ledger-namada/blob/c52229ad26aa0a60c644b44b130b241baffa4c28/app/src/parser_impl_txn.c#L1431 . This covers the last part of https://github.com/Zondax/ledger-namada/issues/48#issue-2372144939 , thanks! However looking at the app v0.0.28, we don't seem to ensure that `v->transfer.shielded_hash` equals `txid` where `txid` is the transaction ID of the MASP `Transaction` inside the `MaspTx` section. If there is no match here, the transaction should be deemed invalid and should not be printed nor be signable.

**Comment by chcmedeiros** [comment]
Just added that check to the fixes branch

**Comment by murisi** [comment]
> Just added that check to the fixes branch

Thanks! Does this cover IBC transactions? I.e. `v->ibc.transfer.shielded_hash`?
