### ISSUE TITLE
Calling `NamadaApp::sign` after `NamadaApp::get_signature` yields `0: Ledger | App Error: | 27012 apdu parameters invalid`

### ISSUE THREAD

**Issue by murisi** [Zondax/ledger-namada#74]
Using the Namada App with the following call sequence:
* `NamadaApp::clean_randomness_buffers`
* `NamadaApp::get_spend_randomness`
* `NamadaApp::get_convert_randomness`
* `NamadaApp::get_output_randomness`
* `NamadaApp::sign_masp_spends`
* `NamadaApp::get_spend_signature`
* `NamadaApp::sign`

results in the error `0: Ledger | App Error: | 27012 apdu parameters invalid` during the call to `NamadaApp::sign`. This error is displayed by our client `namadac` at the point when the Ledger device was supposed to display the transaction.

The error seems to be due to the logic at https://github.com/Zondax/ledger-namada/blob/5ed06a4d6d3347e301cf5afc02aba0e319eef57a/app/src/nvdata.c#L146 clearing the randomness buffers when the last spend signature is retrieved by `NamadaApp::get_spend_signature`. This is problematic because the following call, `NamadaApp::sign`, checks that the number of spend description information objects in the MASP `Transaction` builder is equal to the number of spend randomness parameters during the MASP `Builder` section parsing process. The analogous equinumerosity checks for the convert descriptions and randomness parameters would also fail for the same reason.

**Comment by ainhoa-a** [comment]
Can be closed once https://github.com/Zondax/ledger-namada/pull/69 gets merged
