### ISSUE TITLE
`NamadaApp::sign_masp_spends` sometimes returns `Ledger | App Error: | 28417 apdu sign verify error`

### ISSUE THREAD

**Issue by murisi** [Zondax/ledger-namada#76]
The call `NamadaApp::sign_masp_spends` returns `Ledger | App Error: | 28417 apdu sign verify error` for some transaction blobs. When this error occurs, it's always after the transaction has been displayed on the hardware wallet and "approve" has been pressed. See attached some test vectors showing some examples of successfully signed transactions and an example of a failing transaction.

Looking at the test vectors, it seems that the `convert_indices` field in the `Tx` metadata is a predictor of whether signing will be successful. If this vector is empty or contains exactly one element, signing seems to always be successful.  If the vector has 2 elements and the first is 0, signing also seems to always be successful. Otherwise signing is most likely to fail. This suggests to me that there may be an issue in the fetching of convert descriptions (in `Transaction`s) that correspond to convert description information objects (in the metadata).

[sign_convert_failure.txt](https://github.com/user-attachments/files/17183282/sign_convert_failure.txt)

**Comment by ainhoa-a** [comment]
Can be closed once https://github.com/Zondax/ledger-namada/pull/69 gets merged
