### ISSUE TITLE
Calling `NamadaApp::sign` in new session returns `Ledger | App Error: | 27012 apdu parameters invalid`

### ISSUE THREAD

**Issue by murisi** [Zondax/ledger-namada#78]
Calling `NamadaApp::sign` on a `Tx` that was generated and received its MASP spend authorization signatures in an earlier session and/or on a different device yields the error `Ledger | App Error: | 27012 apdu parameters invalid`. Calling `NamadaApp::sign` like this is desirable if the MASP authorization keys reside on a different device from the keys of the gas payer. See attached an example of a `Tx` that causes this error to occur.
[sessions_testvector.txt](https://github.com/user-attachments/files/17189263/sessions_testvector.txt)

**Comment by ainhoa-a** [comment]
Can be closed once https://github.com/Zondax/ledger-namada/pull/69 gets merged
